#ifndef FILE_DATA_TYPES_HPP
#define FILE_DATA_TYPES_HPP

#include <map>
#include "framework/common/packet.hpp"

class PipelineFrameInfo {
 public:
  PipelineFrameInfo() {}
  ~PipelineFrameInfo() {}
  uint64_t frame_id_;
  uint32_t frame_width;
  uint32_t frame_height;
  std::map<std::string, Packet> node_data_;  // generated by node
};

typedef std::unique_ptr<PipelineFrameInfo> PtrFrameInfo;

#endif
