#ifndef TDL_MODEL_DEFS_H
#define TDL_MODEL_DEFS_H

enum TDL_MODEL_TYPE {
  TDL_MODEL_TYPE_INVALID = 0,
  TDL_MODEL_TYPE_FACE_DETECTION_SCRFD = 1,
  TDL_MODEL_TYPE_FACE_DETECTION_RETINAFACE = 2,
  TDL_MODEL_TYPE_FACE_DETECTION_FACE_MASK = 3,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV8_PERSON_VEHICLE = 4,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV10 = 5,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV3 = 6,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV5 = 7,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV6 = 8,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLO = 9,
  TDL_MODEL_TYPE_OBJECT_DETECTION_MOBILEDETV2_PEDESTRIAN = 10,
  TDL_MODEL_TYPE_FACE_LANDMARKER_LANDMARKERDETV2 = 11,
  TDL_MODEL_TYPE_FACE_FEATURE_BMFACER34 = 12,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV8_HARDHAT = 13,
  TDL_MODEL_TYPE_FACE_ATTRIBUTE_CLS = 14,
  TDL_MODEL_TYPE_FACE_ANTI_SPOOF_CLASSIFICATION = 15,
  TDL_MODEL_TYPE_INSTANCE_SEGMENTATION_YOLOV8 = 16,
  TDL_MODEL_TYPE_KEYPOINT_DETECTION_YOLOV8 = 17,
  TDL_MODEL_TYPE_CLIP_IMAGE = 18,
  TDL_MODEL_TYPE_CLIP_TEXT = 19,
  TDL_MODEL_TYPE_KEYPOINT_DETECTION_SIMCC = 20,
};

#endif
