FROM gitlab-ai.bitmain.vip:4567/bitmain/bmtap2/ubuntu:1.5.10

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
        cmake-gui

# Install Open CV - Warning, this takes absolutely forever
RUN mkdir -p ~/opencv && \
    cd ~/opencv && \
    wget https://github.com/Itseez/opencv/archive/3.4.0.zip && \
    unzip 3.4.0.zip && \
    rm 3.4.0.zip && \
    mv opencv-3.4.0 OpenCV && \
    cd OpenCV && \
    mkdir build && \ 
    cd build && \
    cmake ../ && \
    make -j8 && \
    make install && \ 
    ldconfig

RUN mkdir -p ~/glog cd ~/glog && \
    wget https://github.com/google/glog/archive/v0.3.5.zip && \
    unzip v0.3.5.zip && \
    rm v0.3.5.zip && \
    cd glog-0.3.5 && \
    mkdir build && \ 
    ./configure && \
    make -j8 && \
    make install && \ 
    ldconfig
