#ifndef TDL_MODEL_DEFS_H
#define TDL_MODEL_DEFS_H

enum TDL_MODEL_TYPE {
  TDL_MODEL_TYPE_INVALID = 0,
  TDL_MODEL_TYPE_FACE_DETECTION_SCRFD = 1,
  TDL_MODEL_TYPE_FACE_DETECTION_RETINAFACE = 2,
  TDL_MODEL_TYPE_FACE_DETECTION_FACE_MASK = 3,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV8_PERSON_VEHICLE = 4,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV10 = 5,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV3 = 6,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV5 = 7,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLOV6 = 8,
  TDL_MODEL_TYPE_OBJECT_DETECTION_YOLO = 9,
  TDL_MODEL_TYPE_OBJECT_DETECTION_MOBILEDETV2_PEDESTRIAN = 10,
};

#endif
