#ifndef TDL_MODEL_DEF_H
#define TDL_MODEL_DEF_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  TDL_MODEL_UNKOWN = 0,
  TDL_MODEL_PERSON_PETS_DETECTION,
  TDL_MODEL_PERSON_VEHICLE_DETECTION,
  TDL_MODEL_HAND_FACE_PERSON_DETECTION,
  TDL_MODEL_HEAD_PERSON_DETECTION,
  TDL_MODEL_MOBILEDETV2_PERSON_VEHICLE,
  TDL_MODEL_MOBILEDETV2_VEHICLE,
  TDL_MODEL_MOBILEDETV2_PEDESTRIAN,
  TDL_MODEL_MOBILEDETV2_PERSON_PETS,

  TDL_MODEL_THERMALPERSON,
  TDL_MODEL_HAND_DETECTION,

  TDL_MODEL_DMSLANDMARKERDET,
  TDL_MODEL_LANE_DET,
  TDL_MODEL_LPRNET_TW,
  TDL_MODEL_LPRNET_CN,
  TDL_MODEL_LANDMARK_DET3,
  TDL_MODEL_LP_DETECTION,
  TDL_MODEL_YOLO,
  TDL_MODEL_YOLOV3,
  TDL_MODEL_YOLOV5,
  TDL_MODEL_YOLOV6,
  TDL_MODEL_YOLOV7,
  TDL_MODEL_YOLOX,
  TDL_MODEL_PPYOLOE,
  TDL_MODEL_YOLOV8_DETECTION,
  TDL_MODEL_YOLOV8_SEG,
  TDL_MODEL_YOLOV8_HARDHAT,
  TDL_MODEL_YOLOV10_DETECTION,

  TDL_MODEL_RETINAFACE = 100,
  TDL_MODEL_SCRFDFACE,
  TDL_MODEL_RETINAFACE_IR,
  TDL_MODEL_RETINAFACE_HARDHAT,
  TDL_MODEL_THERMALFACE,
  TDL_MODEL_FACEATTRIBUTE,
  TDL_MODEL_FACEATTRIBUTE_CLS,
  TDL_MODEL_FACERECOGNITION,
  TDL_MODEL_MASKFACERECOGNITION,
  TDL_MODEL_FACEQUALITY,
  TDL_MODEL_MASKCLASSIFICATION,
  TDL_MODEL_FACELANDMARKER,
  TDL_MODEL_FACELANDMARKERDET2,
  TDL_MODEL_FACEMASKDETECTION,
  TDL_MODEL_LIVENESS,
  TDL_MODEL_IRLIVENESS,

  TDL_MODEL_IMAGE_CLASSIFICATION,
  TDL_MODEL_RAW_IMAGE_CLASSIFICATION,
  TDL_MODEL_ISP_IMAGE_CLASSIFICATION,
  TDL_MODEL_EYECLASSIFICATION,
  TDL_MODEL_YAWNCLASSIFICATION,
  TDL_MODEL_SMOKECLASSIFICATION,
  TDL_MODEL_OCCLUSION_CLASSIFICATION,
  TDL_SUPPORTED_CLASSIFICATION_MODEL_MAX,

  TDL_SUPPORTED_RECONGNITION_MODEL = 300,
  TDL_MODEL_OSNET,
  TDL_MODEL_LP_RECONGNITION,
  TDL_SUPPORTED_RECONGNITION_MODEL_MAX,

  TDL_SUPPORTED_POSE_MODEL = 400,
  TDL_MODEL_YOLOV8POSE,
  TDL_MODEL_SIMCC_POSE,
  TDL_MODEL_HRNET_POSE,
  TDL_SUPPORTED_POSE_MODEL_MAX,

  TDL_SUPPORTED_OCR_MODEL = 500,
  TDL_MODEL_OCR_DETECTION,
  TDL_MODEL_OCR_RECOGNITION,
  TDL_SUPPORTED_OCR_MODEL_MAX,

  TDL_SUPPORTED_SOUND_MODEL = 600,
  TDL_MODEL_SOUNDCLASSIFICATION,
  TDL_SUPPORTED_SOUND_MODEL_MAX,

  TDL_SUPPORTED_MOITON_MODEL = 700,
  TDL_MODEL_MOTIONSEGMENTATION,
  TDL_MODEL_HANDCLASSIFICATION,
  TDL_MODEL_HAND_KEYPOINT,
  TDL_MODEL_HAND_KEYPOINT_CLASSIFICATION,
  TDL_SUPPORTED_MOTION_MODEL_MAX,

  TDL_SUPPORTED_DEPTH_MODEL = 800,
  TDL_MODEL_STEREO,
  TDL_SUPPORTED_DEPTH_MODEL_MAX,

  TDL_SUPPORTED_LLM_MODEL = 900,
  TDL_MODEL_CLIP_IMAGE,
  TDL_MODEL_CLIP_TEXT,
  TDL_SUPPORTED_LLM_MODEL_MAX,

  TDL_MODEL_WPODNET,
  TDL_MODEL_DEEPLABV3,
  TDL_MODEL_POLYLANE,
  TDL_MODEL_SUPER_RESOLUTION,
  TDL_MODEL_LSTR,
  TDL_MODEL_END
} cvtdl_model_e;

#ifdef __cplusplus
}
#endif

#endif
